#!/bin/bash 

printf "\033[38;5;111m=> Checking for Curl : \033[39m"
if which curl &> /dev/null;
  then echo -e "\033[38;5;148mOK\033[39m";
  else echo -e "\033[38;5;213mInstalling Curl\033[39m"
  sudo apt-get install curl
  if which curl &> /dev/null;
    then echo -e "\033[38;5;148m=> 'Curl' installed successfully\033[39m";
    else echo -e "\033[38;5;1m=> 'Curl' not installed\033[39m" && exit 1
  fi
fi

printf "\033[38;5;111m=> Checking for Mojolicious : \033[39m"
if which morbo &> /dev/null;
  then echo -e "\033[38;5;148mOK\033[39m";
  else echo -e "\033[38;5;213mInstalling Mojolicious\033[39m"
  curl get.mojolicio.us | sh
  if which morbo &> /dev/null;
    then echo -e "\033[38;5;148m=> 'Mojolicious' installed successfully\033[39m";
    else echo -e "\033[38;5;1m=> 'Mojolicious' not installed\033[39m" && exit 1
  fi
fi

printf "\033[38;5;111m=> Checking for CPanMinus : \033[39m"
if which cpanm &> /dev/null;
  then echo -e "\033[38;5;148mOK\033[39m";
  else echo -e "\033[38;5;213mInstalling CPanMinus\033[39m (Perl Modules)"
  curl -L cpanmin.us | sudo perl - App::cpanminus
  if which cpanm &> /dev/null;
    then echo -e "\033[38;5;148m=> 'CPanMinus' installed successfully\033[39m";
    else echo -e "\033[38;5;1m=> 'CpanMinus' not installed\033[39m" && exit 1
  fi
fi

if which cpanm &> /dev/null;
  then echo -e "\033[38;5;213m=> Installing Perl Dependencies\033[39m"
  sudo cpanm Mojolicious::Plugin::Config
  sudo cpanm Try::Tiny
  sudo cpanm DBIx::Simple
  sudo cpanm Mojolicious::Plugin::TtRenderer::Engine
  sudo cpanm Mojolicious::Plugin::I18N
  sudo cpanm Text::Template
  echo -e "\033[38;5;148m=> 'Perl Dependencies' installed successfully\033[39m";
fi

echo -e "\033[38;5;111m=> Done\033[39m"
